package oak

import (
	"github.com/oakmound/oak/v4/alg/intgeom"
	"github.com/oakmound/oak/v4/event"

	okey "github.com/oakmound/oak/v4/key"
	omouse "github.com/oakmound/oak/v4/mouse"
)

// The following block defines events generated by oak during scene execution
var (
	// ViewportUpdate is triggered when the position of of the viewport changes
	ViewportUpdate = event.RegisterEvent[intgeom.Point2]()
	// OnStop is triggered when the engine is stopped, e.g. when a window's close
	// button is clicked.
	OnStop = event.RegisterEvent[struct{}]()
	// FocusGain is triggered when a window gains focus
	FocusGain = event.RegisterEvent[struct{}]()
	// FocusLoss is triggered when a window loses focus
	FocusLoss = event.RegisterEvent[struct{}]()
	// InputChange is triggered when the most recent input device changes (e.g. keyboard to joystick or vice versa). It
	// is only sent if Config.TrackInputChanges is true when Init is called.
	InputChange = event.RegisterEvent[InputType]()
)

func (w *Window) inputLoop() { _ = "STUB: not implemented"; return }

// We only currently respond to death lifecycle events.

// If you are in focused state, we don't care how you got there

// If the last state was focused, this means the app is out of focus
// otherwise, we're visible for the first time

// Send key events
//
// Key events have two varieties:
// The "KeyDown" and "KeyUp" events, which trigger for all keys
// and specific "KeyDown$key", etc events which trigger only for $key.
// The specific key that is pressed is passed as the data interface for
// the former events, but not for the latter.

// Send mouse events
//
// Mouse events are parsed based on their button
// and direction into an event name and then triggered:
// 'MousePress', 'MouseRelease', 'MouseScrollDown', 'MouseScrollUp', and 'MouseDrag'
//
// The basic event name is meant for entities which
// want to respond to the mouse event happening -anywhere-.
//
// For events which have mouse collision enabled, they'll receive
// $eventName+"On" when the event occurs within their collision area.
//
// Mouse events all receive an x, y, and button string.

// The event triggered for mouse events has the same scaling as the
// render and collision space. I.e. if the viewport is at 0, the mouse's
// position is exactly the same as the position of a visible entity
// on screen. When not at zero, the offset will be exactly the viewport.

// Size events update what we scale the screen to

// TriggerKeyDown triggers a software-emulated keypress.
// This should be used cautiously when the keyboard is in use.
// From the perspective of the event handler this is indistinguishable
// from a real keypress.
func (w *Window) TriggerKeyDown(e okey.Event) { _ = "STUB: not implemented"; return }

// TriggerKeyUp triggers a software-emulated key release.
// This should be used cautiously when the keyboard is in use.
// From the perspective of the event handler this is indistinguishable
// from a real key release.
func (w *Window) TriggerKeyUp(e okey.Event) { _ = "STUB: not implemented"; return }

// TriggerKeyHeld triggers a software-emulated key hold signal.
// This should be used cautiously when the keyboard is in use.
// From the perspective of the event handler this is indistinguishable
// from a real key hold signal.
func (w *Window) TriggerKeyHeld(e okey.Event) { _ = "STUB: not implemented"; return }

// TriggerMouseEvent triggers a software-emulated mouse event.
// This should be used cautiously when the mouse is in use.
// From the perspective of the event handler this is indistinguishable
// from a real key mouse press or movement.
func (w *Window) TriggerMouseEvent(mevent omouse.Event) { _ = "STUB: not implemented"; return }
