// Code generated by foptgen; DO NOT EDIT.

package entities

import (
	"image/color"

	"github.com/oakmound/oak/v4/alg/floatgeom"
	"github.com/oakmound/oak/v4/collision"
	"github.com/oakmound/oak/v4/event"
	"github.com/oakmound/oak/v4/render"
	"github.com/oakmound/oak/v4/render/mod"
)

type Option func(Generator) Generator

func WithPosition(v floatgeom.Point2) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithDimensions(v floatgeom.Point2) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithSpeed(v floatgeom.Point2) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithParent(v event.Caller) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithColor(v color.Color) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithRenderable(v render.Renderable) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithMod(v mod.Mod) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithLabel(v collision.Label) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithDrawLayers(v []int) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithUseMouseTree(v bool) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithWithoutCollision(v bool) Option { _ = "STUB: not implemented"; return *new(Option) }

func WithChildren(v [][]Option) Option { _ = "STUB: not implemented"; return *new(Option) }
