// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package windriver

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

var (
	modmsimg32 = windows.NewLazySystemDLL("msimg32.dll")
	modgdi32   = windows.NewLazySystemDLL("gdi32.dll")
	moduser32  = windows.NewLazySystemDLL("user32.dll")

	procAlphaBlend             = modmsimg32.NewProc("AlphaBlend")
	procBitBlt                 = modgdi32.NewProc("BitBlt")
	procCreateCompatibleBitmap = modgdi32.NewProc("CreateCompatibleBitmap")
	procCreateCompatibleDC     = modgdi32.NewProc("CreateCompatibleDC")
	procCreateDIBSection       = modgdi32.NewProc("CreateDIBSection")
	procCreateSolidBrush       = modgdi32.NewProc("CreateSolidBrush")
	procDeleteDC               = modgdi32.NewProc("DeleteDC")
	procDeleteObject           = modgdi32.NewProc("DeleteObject")
	procFillRect               = moduser32.NewProc("FillRect")
	procModifyWorldTransform   = modgdi32.NewProc("ModifyWorldTransform")
	procSelectObject           = modgdi32.NewProc("SelectObject")
	procSetGraphicsMode        = modgdi32.NewProc("SetGraphicsMode")
	procSetWorldTransform      = modgdi32.NewProc("SetWorldTransform")
	procStretchBlt             = modgdi32.NewProc("StretchBlt")
	procGetDeviceCaps          = modgdi32.NewProc("GetDeviceCaps")
)

func _AlphaBlend(dcdest syscall.Handle, xoriginDest int32, yoriginDest int32, wDest int32, hDest int32, dcsrc syscall.Handle, xoriginSrc int32, yoriginSrc int32, wsrc int32, hsrc int32, ftn uintptr) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func _BitBlt(dcdest syscall.Handle, xdest int32, ydest int32, width int32, height int32, dcsrc syscall.Handle, xsrc int32, ysrc int32, rop uint32) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func _CreateCompatibleBitmap(dc syscall.Handle, width int32, height int32) (bitmap syscall.Handle, err error) {
	_ = "STUB: not implemented"
	return *new(syscall.Handle), nil
}

func _CreateCompatibleDC(dc syscall.Handle) (newdc syscall.Handle, err error) {
	_ = "STUB: not implemented"
	return *new(syscall.Handle), nil
}

func _CreateDIBSection(dc syscall.Handle, bmi *_BITMAPINFO, usage uint32, bits **byte, section syscall.Handle, offset uint32) (bitmap syscall.Handle, err error) {
	_ = "STUB: not implemented"
	return *new(syscall.Handle), nil
}

func _CreateSolidBrush(color _COLORREF) (brush syscall.Handle, err error) {
	_ = "STUB: not implemented"
	return *new(syscall.Handle), nil
}

func _DeleteDC(dc syscall.Handle) (err error) { _ = "STUB: not implemented"; return nil }

func _DeleteObject(object syscall.Handle) (err error) { _ = "STUB: not implemented"; return nil }

func _FillRect(dc syscall.Handle, rc *_RECT, brush syscall.Handle) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func _ModifyWorldTransform(dc syscall.Handle, x *_XFORM, mode uint32) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func _SelectObject(dc syscall.Handle, gdiobj syscall.Handle) (newobj syscall.Handle, err error) {
	_ = "STUB: not implemented"
	return *new(syscall.Handle), nil
}

func _SetGraphicsMode(dc syscall.Handle, mode int32) (oldmode int32, err error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func _SetWorldTransform(dc syscall.Handle, x *_XFORM) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func _StretchBlt(dcdest syscall.Handle, xdest int32, ydest int32, wdest int32, hdest int32, dcsrc syscall.Handle, xsrc int32, ysrc int32, wsrc int32, hsrc int32, rop uint32) (err error) {
	_ = "STUB: not implemented"
	return nil
}

func _GetDeviceCaps(dc syscall.Handle, index int32) (ret int32) {
	_ = "STUB: not implemented"
	return 0
}
